version: '3.8'
services:
  backend_api:
    volumes:
      - ./backend/api:/app
  backend_worker:
    volumes:
      - ./backend/worker/app:/app
      - ./backend/worker/model/dogsearch/model:/app/dogsearch/model
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
