version: '3.8'
services:
  backend_db:
    build: ./backend/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME} 
    volumes:
      - backend_data:/data/db
  backend_api:
    build:
      context: ./backend/api
    depends_on:
      - backend_db
    environment:
      - DB_HOST=backend_db
      - DB_NAME
  proxy:
    build: ./proxy
    ports:
      - ${PORT}:80
    depends_on:
      - backend_api
volumes:
  backend_data: {}
